# Basic Configuration
title: Your Site Title
description: A brief description of your site
url: "https://yourusername.github.io"
baseurl: "/Test-Alter-Documentation"

# Markdown Processor
markdown: kramdown

kramdown:
  toc_levels: "1, 2"

# Kramdown Options
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-toc
  - jekyll-anchor-links

jekyll-toc:
  maxdepth: 2


# Relative Links Configuration
relative_links:
  enabled: true
  collections: true

# Include Specific Files
include:
  - README.md
  - LICENSE.md

# Exclude Default Folders
exclude:
  - "node_modules"
  - "vendor"
  - ".gitignore"
  - ".travis.yml"
  - ".github"

# Theme
theme: jekyll-theme-hacker # You can change this to any Jekyll theme

# Build Settings
highlighter: rouge